meta_product_name: "Perfect Night"
meta_title: "Perfect Night - Ressentez la magie de la soirée parfaite"
meta_description: "C’est une application mobile qui te propose des activités différentes pour passer une bonne soirée."
meta_image: "cover.jpg"
twitter_account: "@perfectnight"
